# Site settings
title: michelle plunkett
email: michellejplunkett@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michelle Plunkett's website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michelle-plunkett.com" # the base hostname & protocol for your site
github_username:  michelleplunkett

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
highlighter: rouge
excerpt_separator: <!--more-->

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  projects:
    output: true
    permalink: /projects/:path/