# Site settings
title: Michelle Plunkett
email: michellep1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Michelle Plunkett's website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michelle-plunkett.com" # the base hostname & protocol for your site
github_username:  michelleplunkett

# Build settings
markdown: redcarpet
highlighter: pygments
github: https://github.com/michelleplunkett/michelleplunkett.github.io
permalink: /blog/:year/:month/:day/:title
