# Site settings
title: Michelle Plunkett
email: michellep1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michelle Plunkett's Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://michelle-plunkett.com" # the base hostname & protocol for your site
github_username:  michelleplunkett

permalink: /:title/

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
highlighter: rouge
excerpt_separator: <!--more-->

# Pagination
paginate: 5
paginate_path: "/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  projects:
    output: true
    permalink: /projects/:path/
