# Site settings
title: Michelle Plunkett
email: michellejplunkett@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Michelle Plunkett's website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michelle-plunkett.com" # the base hostname & protocol for your site
github_username:  michelleplunkett

# Build settings
markdown: redcarpet
highlighter: rouge
github: https://github.com/michelleplunkett/michelleplunkett.github.io

#Handling Reading
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
